# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "shard1" do |shard1|
    shard1.vm.box_check_update = false
    shard1.vm.box = "ubuntu/trusty64"
    shard1.vm.network "public_network", ip: "10.0.1.10", bridge: "wlan0"
    shard1.vm.synced_folder "./shard1/mongodb", "/etc/mongodb"
    shard1.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard1.vm.provision :shell, path: "./shard1/bootstrap_shard1.sh"
  end

  config.vm.define "shard1rep1" do |shard1rep1|
    shard1rep1.vm.box_check_update = false
    shard1rep1.vm.box = "ubuntu/trusty64"
    shard1rep1.vm.network "public_network", ip: "10.0.1.11", bridge: "wlan0"
    shard1rep1.vm.synced_folder "./shard1rep1/mongodb", "/etc/mongodb"
    shard1rep1.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard1rep1.vm.provision :shell, path: "./shard1rep1/bootstrap_shard1rep1.sh"
  end

  config.vm.define "shard1rep2" do |shard1rep2|
    shard1rep2.vm.box_check_update = false
    shard1rep2.vm.box = "ubuntu/trusty64"
    shard1rep2.vm.network "public_network", ip: "10.0.1.12", bridge: "wlan0"
    shard1rep2.vm.synced_folder "./shard1rep2/mongodb", "/etc/mongodb"
    shard1rep2.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard1rep2.vm.provision "file", source: "./supporting_files/setup_shard1rep.js", destination: "~/setup_shard1rep.js"
    shard1rep2.vm.provision :shell, path: "./shard1rep2/bootstrap_shard1rep2.sh"
  end

  config.vm.define "shard2" do |shard2|
    shard2.vm.box_check_update = false
    shard2.vm.box = "ubuntu/trusty64"
    shard2.vm.network "public_network", ip: "10.0.1.20", bridge: "wlan0"
    shard2.vm.synced_folder "./shard2/mongodb", "/etc/mongodb"
    shard2.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard2.vm.provision :shell, path: "./shard2/bootstrap_shard2.sh"
  end


  config.vm.define "shard2rep1" do |shard2rep1|
    shard2rep1.vm.box_check_update = false
    shard2rep1.vm.box = "ubuntu/trusty64"
    shard2rep1.vm.network "public_network", ip: "10.0.1.21", bridge: "wlan0"
    shard2rep1.vm.synced_folder "./shard2rep1/mongodb", "/etc/mongodb"
    shard2rep1.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard2rep1.vm.provision :shell, path: "./shard2rep1/bootstrap_shard2rep1.sh"
  end

  config.vm.define "shard2rep2" do |shard2rep2|
    shard2rep2.vm.box_check_update = false
    shard2rep2.vm.box = "ubuntu/trusty64"
    shard2rep2.vm.network "public_network", ip: "10.0.1.22", bridge: "wlan0"
    shard2rep2.vm.synced_folder "./shard2rep2/mongodb", "/etc/mongodb"
    shard2rep2.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    shard2rep2.vm.provision "file", source: "./supporting_files/setup_shard2rep.js", destination: "~/setup_shard2rep.js"
    shard2rep2.vm.provision :shell, path: "./shard2rep2/bootstrap_shard2rep2.sh"
  end

  config.vm.define "conf1" do |conf1|
    conf1.vm.box_check_update = false
    conf1.vm.box = "ubuntu/trusty64"
    conf1.vm.network "public_network", ip: "10.0.1.3", bridge: "wlan0"
    conf1.vm.network "forwarded_port", guest: 30000, host: 30000
    conf1.vm.synced_folder "./conf1/mongodb", "/etc/mongodb"
    conf1.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    conf1.vm.provision "file", source: "./supporting_files/add_shards.js", destination: "~/add_shards.js"
    conf1.vm.provision "file", source: "./supporting_files/run_mongos1.sh", destination: "~/run_mongos1.sh"
    conf1.vm.provision :shell, path: "./conf1/bootstrap_conf1.sh"
  end

  config.vm.define "conf2" do |conf2|
    conf2.vm.box_check_update = false
    conf2.vm.box = "ubuntu/trusty64"   
    conf2.vm.network "public_network", ip: "10.0.1.4", bridge: "wlan0"
    conf2.vm.network "forwarded_port", guest: 40000, host: 40000
    conf2.vm.synced_folder "./conf2/mongodb", "/etc/mongodb"
    conf2.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    conf2.vm.provision "file", source: "./supporting_files/run_mongos2.sh", destination: "~/run_mongos2.sh"
    conf2.vm.provision :shell, path: "./conf2/bootstrap_conf2.sh"
  end

  config.vm.define "conf3" do |conf3|
    conf3.vm.box_check_update = false
    conf3.vm.box = "ubuntu/trusty64"
    conf3.vm.network "public_network", ip: "10.0.1.5", bridge: "wlan0"
    conf3.vm.network "forwarded_port", guest: 50000, host: 50000
    conf3.vm.synced_folder "./conf3/mongodb", "/etc/mongodb"
    conf3.vm.provision "file", source: "./supporting_files/mongo", destination: "~/"
    conf3.vm.provision "file", source: "./supporting_files/run_mongos3.sh", destination: "~/run_mongos3.sh"
    conf3.vm.provision :shell, path: "./conf3/bootstrap_conf3.sh"
  end

end
