#!/bin/bash

# mongos - Startup script for mongos

# chkconfig: 35 85 15
# description: Mongos router process.
# processname: mongos
# config: /etc/mongos.conf
# pidfile: /var/run/mongodb/mongos.pid

. /etc/rc.d/init.d/functions

CONFIGFILE="/etc/mongos.conf"
OPTIONS=" -f $CONFIGFILE"
SYSCONFIG="/etc/sysconfig/mongos"
RETRIES="5"
SLEEP_RETRY="30"

PIDFILE=`awk -F'[:=]' -v IGNORECASE=1 '/^[[:blank:]]*pidfilepath[[:blank:]]*[:=][[:blank:]]*/{print $2}' "$CONFIGFILE" | tr -d '[:blank:]'`
PIDDIR=`dirname $PIDFILE`

mongos=${MONGOS-/usr/bin/mongos}

MONGO_USER=mongod
MONGO_GROUP=mongod

if [ -f "$SYSCONFIG" ]; then
    . "$SYSCONFIG"
fi

NUMACTL_ARGS="--interleave=all"
if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null
then
    NUMACTL="numactl $NUMACTL_ARGS"
else
    NUMACTL=""
fi

start()
{
    if [ ! -d $PIDDIR ]; then
        install -d -m 0755 -o $MONGO_USER -g $MONGO_GROUP $PIDDIR
    fi

    ulimit -f unlimited
    ulimit -t unlimited
    ulimit -v unlimited
    ulimit -n 64000
    ulimit -m unlimited
    ulimit -u 32000

    MONGOS_STARTED=42

    while [ $MONGOS_STARTED -ne 0 -a $RETRIES -ne 0 ]
    do
        echo -n $"Starting mongos try $((6-$RETRIES)): "
        sleep $SLEEP_RETRY
        RETRIES=$[$RETRIES-1]
        daemon --user "$MONGO_USER" --check $mongos "$NUMACTL $mongos $OPTIONS >/dev/null 2>&1"
        MONGOS_STARTED=$?
    done

    echo
    [ $MONGOS_STARTED -eq 0 ] && touch /var/lock/subsys/mongos
}

stop()
{
    echo -n $"Stopping mongos: "
    killproc -p "$PIDFILE" -d 300 /usr/bin/mongos
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/mongos
}

restart () {
        stop
        start
}


RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f /var/lock/subsys/mongos ] && restart || :
    ;;
  status)
    status $mongos
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL
